const DEFAULT_DATASETS = [
  "data/vocabularies.json",
  "data/research-20260810-semiotics-complexity.json",
  "data/meta-vocabularies.json",
  "data/research-20260810-editorial.json",
];

const DEFAULT_RELATION_DATASETS = [
  "data/relations.json",
  "data/relations-20260810-editorial.json",
];

const state = { items: [], query: "", feeling: null, field: null, activeItemId: null, catalog: { schema_version: 1, datasets: DEFAULT_DATASETS, relation_datasets: DEFAULT_RELATION_DATASETS, defaults: { primary_language: "ja", formal_status: "established_term", aliases: [] }, formal_status_labels: {}, field_labels: {}, taxonomy: [], terms: {}, search_contrasts: [] } };
const searchInput=document.querySelector("#searchInput"),feelingChips=document.querySelector("#feelingChips"),fieldFilters=document.querySelector("#fieldFilters"),vocabularyGrid=document.querySelector("#vocabularyGrid"),resultCount=document.querySelector("#resultCount"),emptyState=document.querySelector("#emptyState"),clearFilters=document.querySelector("#clearFilters"),randomButton=document.querySelector("#randomButton");
const normalize=v=>String(v??"").trim().toLocaleLowerCase("ja");
function escapeHtml(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")} function escapeAttribute(v){return escapeHtml(v)}
function fieldLabel(f){return state.catalog.field_labels?.[f]??f} function fieldGroup(f){return(state.catalog.taxonomy??[]).find(g=>(g.fields??[]).includes(f))??null} function formalStatusLabel(i){return state.catalog.formal_status_labels?.[i.formal_status]??i.formal_status??""}
function displayNames(i){const j=Boolean(String(i.ja??"").trim()),e=Boolean(String(i.term??"").trim()),en=i.primary_language==="en"||!j;return en?{primary:i.term,secondary:j?i.ja:"",primaryLanguage:"en"}:{primary:i.ja,secondary:e?i.term:"",primaryLanguage:"ja"}}
function uniqueSorted(v){return[...new Set(v.filter(Boolean))].sort((a,b)=>fieldLabel(a).localeCompare(fieldLabel(b),"ja"))} function mergeItems(...c){const m=new Map();c.flat().forEach(i=>{if(i?.id)m.set(i.id,i)});return[...m.values()]}
function applyCatalogMetadata(i){const d=state.catalog.defaults??{},m=state.catalog.terms?.[i.id]??{},aliases=[...new Set([...(d.aliases??[]),...(i.aliases??[]),...(m.aliases??[])].filter(Boolean))];return{...d,...i,...m,aliases}}
function buildSearchText(i){const g=(i.fields??[]).map(fieldGroup).filter(Boolean).map(x=>x.label);return normalize([i.ja,i.term,...(i.aliases??[]),i.one_liner,i.description,i.why_selected,formalStatusLabel(i),...(i.fields??[]),...(i.fields??[]).map(fieldLabel),...g,...(i.feelings??[])].join(" "))}
function filteredItems(){const q=normalize(state.query);return state.items.filter(i=>(!q||buildSearchText(i).includes(q))&&(!state.feeling||(i.feelings??[]).includes(state.feeling))&&(!state.field||(i.fields??[]).includes(state.field)))}
function renderFeelingChips(){const f=[...new Set(state.items.flatMap(i=>i.feelings??[]))].filter(Boolean).sort((a,b)=>a.localeCompare(b,"ja"));feelingChips.innerHTML=f.map(x=>`<button class="chip${state.feeling===x?' is-active':''}" type="button" data-feeling="${escapeAttribute(x)}" aria-pressed="${state.feeling===x}">${escapeHtml(x)}</button>`).join("")}
function fieldButton(f){return`<button class="field-button${state.field===f?' is-active':''}" type="button" data-field="${escapeAttribute(f)}" aria-pressed="${state.field===f}">${escapeHtml(fieldLabel(f))}</button>`}
function renderFieldFilters(){const a=uniqueSorted(state.items.flatMap(i=>i.fields??[])),s=new Set(a),u=new Set(),g=[];for(const x of state.catalog.taxonomy??[]){const f=(x.fields??[]).filter(y=>s.has(y));if(!f.length)continue;f.forEach(y=>u.add(y));g.push({label:x.label,fields:f})}const r=a.filter(x=>!u.has(x));if(r.length)g.push({label:"その他",fields:r});fieldFilters.innerHTML=(g.length?g.map(x=>`<div class="field-group"><p class="field-group-label">${escapeHtml(x.label)}</p><div class="field-group-buttons">${x.fields.map(fieldButton).join("")}</div></div>`):a.map(fieldButton)).join("")}
function itemNameById(id){const i=state.items.find(x=>x.id===id);return i?displayNames(i).primary:id}
function renderCard(i){const n=displayNames(i),pc=n.primaryLanguage==="en"?" card-term-en":"",fields=(i.fields??[]).slice(0,4).map(f=>`<span class="mini-tag">${escapeHtml(fieldLabel(f))}</span>`).join(""),related=(i.related??[]).slice(0,3).map(itemNameById),rl=related.length?`<p class="card-related"><span>周辺</span>${escapeHtml(related.join(" ・ "))}</p>`:"",sn=n.secondary?`<p class="card-en">${escapeHtml(n.secondary)}</p>`:"";return`<article class="vocab-card" id="${escapeAttribute(i.id)}" role="button" tabindex="0" data-open-term="${escapeAttribute(i.id)}" aria-label="${escapeAttribute(n.primary)}を読む"><div class="card-topline"><div><h3 class="card-term${pc}">${escapeHtml(n.primary)}</h3>${sn}</div><span class="read-mark" aria-hidden="true">↗</span></div><p class="one-liner">${escapeHtml(i.one_liner)}</p><div class="mini-tags">${fields}</div>${rl}</article>`}
function renderResults(){const i=filteredItems();resultCount.textContent=i.length+"語";emptyState.hidden=i.length!==0;vocabularyGrid.innerHTML=i.map(renderCard).join("")}
function render(){renderFeelingChips();renderFieldFilters();renderResults()} function resetFilters(){state.query="";state.feeling=null;state.field=null;searchInput.value="";render()}
function openRandomItem(){const c=filteredItems(),items=c.length?c:state.items;if(!items.length)return;const i=items[Math.floor(Math.random()*items.length)],card=document.getElementById(i.id);if(!card){resetFilters();requestAnimationFrame(openRandomItem);return}card.click()}
searchInput.addEventListener("input",e=>{state.query=e.target.value;renderResults()});feelingChips.addEventListener("click",e=>{const b=e.target.closest("[data-feeling]");if(!b)return;state.feeling=state.feeling===b.dataset.feeling?null:b.dataset.feeling;render()});fieldFilters.addEventListener("click",e=>{const b=e.target.closest("[data-field]");if(!b)return;state.field=state.field===b.dataset.field?null:b.dataset.field;render()});clearFilters.addEventListener("click",resetFilters);randomButton?.addEventListener("click",openRandomItem);
async function loadJson(path){const p=String(path).replace(/^\.\//,""),urls=["./"+p+"?v="+Date.now(),"https://raw.githubusercontent.com/silovar-uk/vocabularies/main/"+p];let last;for(const url of urls)try{const r=await fetch(url,{cache:"no-store"});if(!r.ok)throw new Error("HTTP "+r.status);return await r.json()}catch(e){last=e;console.warn("Data load failed:",url,e)}throw last??new Error("Data could not be loaded: "+p)}
async function loadCatalog(){const c=await loadJson("data/catalog.json");if(!c||Array.isArray(c)||typeof c!=="object")throw new Error("Catalog data is not an object");return c}
async function loadVocabularyData(){const d=state.catalog.datasets?.length?state.catalog.datasets:DEFAULT_DATASETS,c=await Promise.all(d.map(async p=>{const x=await loadJson(p);if(!Array.isArray(x))throw new Error(p+" is not an array");return x}));return mergeItems(...c).map(applyCatalogMetadata)}
async function init(){render();try{state.catalog={...state.catalog,...(await loadCatalog())}}catch(e){console.error("Catalog load failed:",e)}try{state.items=await loadVocabularyData();window.vocabularyStudyItems=state.items;render();window.dispatchEvent(new CustomEvent('vocabulary-items-ready',{detail:{count:state.items.length}}))}catch(e){console.error(e);resultCount.textContent=state.items.length+"語（データ取得失敗）";vocabularyGrid.insertAdjacentHTML("beforeend",'<div class="load-warning"><strong>語彙データの取得に失敗しました。</strong><br>この画面を再読み込みしてください。</div>')}}init();